services:
  - type: web
    name: my-web-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils
      pip install -r requirements.txt
    startCommand: python app.py
